name: Docker Image CI

on:
  push:
    branches:
      - johnvy  # Se activa solo para la rama johnvy
  pull_request:
    branches:
      - johnvy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso para clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v2

    # Configurar Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Iniciar sesi√≥n en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construir la imagen Docker
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-nginx-server .

    # Hacer push de la imagen a Docker Hub
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-nginx-server
